'''
Created on 28 feb. 2020

@author: marin
'''
import tkinter as tk
ventanaCalculadora = tk.Tk()
ventanaCalculadora.title("Calculadora")
ventanaCalculadora.geometry('225x292')
txtTitulo= tk.Label(ventanaCalculadora,text= "CALCULADORA CON PACK",bg="white",fg="black")
txtTitulo.pack()
cajaMantisa = tk.Entry(ventanaCalculadora)
cajaMantisa.pack(fill=tk.X)
panel= tk.Frame(ventanaCalculadora,width=400,height=100)
panel.pack()
btnLimpiarMemoria = tk.Button(panel, text= "MC")
btnLimpiarMemoria.pack(side=tk.LEFT, ipadx=2,ipady=2)
btnMR = tk.Button(panel, text= "MR")
btnMR.pack(side=tk.LEFT, ipadx=2,ipady=2)
btnMemoriaSumar = tk.Button(panel, text= "M +")
btnMemoriaSumar.pack(side=tk.LEFT, ipadx=5,ipady=5)
btnMemoriaRestar = tk.Button(panel, text= "M - ")
btnMemoriaRestar.pack(side=tk.LEFT, ipadx=5,ipady=5)
btnMS = tk.Button(panel, text= "MS")
btnMS.pack(side=tk.LEFT, ipadx=5,ipady=5)
btnMv = tk.Button(panel, text= "M")
btnMv.pack(side=tk.LEFT, ipadx=5,ipady=5)
panel1= tk.Frame(ventanaCalculadora,width=400,height=100)
panel1.pack()
btnPorciento = tk.Button(panel1, text= "  %  ")
btnPorciento.pack(side=tk.LEFT, ipadx=5,ipady=5)
btnRaiz = tk.Button(panel1, text= "  CE  ")
btnRaiz.pack(side=tk.LEFT, ipadx=5,ipady=5)
btnPtencia = tk.Button(panel1, text= " C ")
btnPtencia.pack(side=tk.LEFT, ipadx=5,ipady=5)
btnBorrar= tk.Button(panel1, text= "  <-  ")
btnBorrar.pack(side=tk.LEFT, ipadx=5,ipady=5)
#=======================================
panel2= tk.Frame(ventanaCalculadora, width=400,height=100)
panel2.pack()
btnIgual = tk.Button(panel2, text= "  1/x  ")
btnIgual.pack(side=tk.LEFT, ipadx=5,ipady=5)
btnPunto = tk.Button(panel2, text= "  x^2  ")
btnPunto.pack(side=tk.LEFT, ipadx=5,ipady=5)
btn0 = tk.Button(panel2, text= "  SQRT  ")
btn0.pack(side=tk.LEFT, ipadx=5,ipady=5)
btnMM = tk.Button(panel2, text= "  /  ")
btnMM.pack(side=tk.LEFT, ipadx=5,ipady=5)

##===================
panel3= tk.Frame(ventanaCalculadora,width=400,height=100)
panel3.pack()
btn1 = tk.Button(panel3, text= "  7  ")
btn1.pack(side=tk.LEFT, ipadx=5,ipady=5)
btn2 = tk.Button(panel3, text= "  8  ")
btn2.pack(side=tk.LEFT, ipadx=5,ipady=5)
btn3 = tk.Button(panel3, text= "  9  ")
btn3.pack(side=tk.LEFT, ipadx=5,ipady=5)
btnMas = tk.Button(panel3, text= "  X  ")
btnMas.pack(side=tk.LEFT, ipadx=5,ipady=5)
panel4= tk.Frame(ventanaCalculadora, width=400,height=400)
panel4.pack()
btn1 = tk.Button(panel4, text= "  4  ")
btn1.pack(side=tk.LEFT, ipadx=5,ipady=5)
btn2 = tk.Button(panel4, text= "  5  ")
btn2.pack(side=tk.LEFT, ipadx=5,ipady=5)
btn3 = tk.Button(panel4, text= "  6  ")
btn3.pack(side=tk.LEFT, ipadx=5,ipady=5)
btnMas = tk.Button(panel4, text= "  -  ")
btnMas.pack(side=tk.LEFT, ipadx=5,ipady=5)
panel5= tk.Frame(ventanaCalculadora,width=400,height=100)
panel5.pack()
btn1 = tk.Button(panel5, text= "  1  ")
btn1.pack(side=tk.LEFT, ipadx=5,ipady=5)
btn2 = tk.Button(panel5, text= "  2  ")
btn2.pack(side=tk.LEFT, ipadx=5,ipady=5)
btn3 = tk.Button(panel5, text= "  3  ")
btn3.pack(side=tk.LEFT, ipadx=5,ipady=5)
btnMas = tk.Button(panel5, text= "  +  ")
btnMas.pack(side=tk.LEFT, ipadx=5,ipady=5)
panel6= tk.Frame(ventanaCalculadora,width=400,height=100)
panel6.pack()
btn1 = tk.Button(panel6, text= "  +/-  ")
btn1.pack(side=tk.LEFT, ipadx=5,ipady=5)
btn2 = tk.Button(panel6, text= "  0  ")
btn2.pack(side=tk.LEFT, ipadx=5,ipady=5)
btn3 = tk.Button(panel6, text= "  .  ")
btn3.pack(side=tk.LEFT, ipadx=5,ipady=5)
btnMas = tk.Button(panel6, text= "  =  ")
btnMas.pack(side=tk.LEFT, ipadx=5,ipady=5)
ventanaCalculadora.mainloop()