'''
Created on 26 feb. 2020

@author: marin
'''
import tkinter as tk 
from tkinter import Label
ventanaPrincipal = tk.Tk()
ventanaPrincipal.title("Calculadora")
ventanaPrincipal.geometry('303x470')
#Inician los botones para la calculadora
btnMasMenos = tk.Button(ventanaPrincipal,text="+/_", bg = "white", fg = "black")
btnMasMenos.place(x=0, y=422, width=75,height=48)
btnCero = tk.Button(ventanaPrincipal,text="0", bg = "white", fg = "black")
btnCero.place(x=76, y=422, width=75,height=48)
btnPunto = tk.Button(ventanaPrincipal,text=".", bg = "white", fg = "black")
btnPunto.place(x=152, y=422, width=75,height=48)
btnIgual = tk.Button(ventanaPrincipal,text="=", bg = "white", fg = "black")
btnIgual.place(x=228, y=422, width=75,height=48)
btnUno = tk.Button(ventanaPrincipal,text="1", bg = "white", fg = "black")
btnUno.place(x=0, y=375, width=75,height=48)
btnDos = tk.Button(ventanaPrincipal,text="2", bg = "white", fg = "black")
btnDos.place(x=76, y=375, width=75,height=48)
btnTres = tk.Button(ventanaPrincipal,text="3", bg = "white", fg = "black")
btnTres.place(x=152, y=375, width=75,height=48)
btnMas = tk.Button(ventanaPrincipal,text="+", bg = "white", fg = "black")
btnMas.place(x=228, y=375, width=75,height=48)
btnCuatro = tk.Button(ventanaPrincipal,text="4", bg = "white", fg = "black")
btnCuatro.place(x=0, y=328, width=75,height=48)
btnCinco = tk.Button(ventanaPrincipal,text="5", bg = "white", fg = "black")
btnCinco.place(x=76, y=328, width=75,height=48)
btnSeis = tk.Button(ventanaPrincipal,text="6", bg = "white", fg = "black")
btnSeis.place(x=152, y=328, width=75,height=48)
btnMenos = tk.Button(ventanaPrincipal,text="-", bg = "white", fg = "black")
btnMenos.place(x=228, y=328, width=75,height=48)
btnNueve = tk.Button(ventanaPrincipal,text="7", bg = "white", fg = "black")
btnNueve.place(x=0, y=281, width=75,height=48)
btnOcho = tk.Button(ventanaPrincipal,text="8", bg = "white", fg = "black")
btnOcho.place(x=76, y=281, width=75,height=48)
btnSiete = tk.Button(ventanaPrincipal,text="9", bg = "white", fg = "black")
btnSiete.place(x=152, y=281, width=75,height=48)
btnPor = tk.Button(ventanaPrincipal,text="X", bg = "white", fg = "black")
btnPor.place(x=228, y=281, width=75,height=48)
btnCe = tk.Button(ventanaPrincipal,text="CE", bg = "white", fg = "black")
btnCe.place(x=0, y=234, width=75,height=48)
btnC = tk.Button(ventanaPrincipal,text="C", bg = "white", fg = "black")
btnC.place(x=76, y=234, width=75,height=48)
btnBorrar = tk.Button(ventanaPrincipal,text="<-", bg = "white", fg = "black")
btnBorrar.place(x=152, y=234, width=75,height=48)
btnDivision = tk.Button(ventanaPrincipal,text="/", bg = "white", fg = "black")
btnDivision.place(x=228, y=234, width=75,height=48)
btnPorc = tk.Button(ventanaPrincipal,text="%", bg = "white", fg = "black")
btnPorc.place(x=0, y=187, width=75,height=48)
btnRaiz = tk.Button(ventanaPrincipal,text="SQRT", bg = "white", fg = "black")
btnRaiz.place(x=76, y=187, width=75,height=48)
btnXC = tk.Button(ventanaPrincipal,text="X^2", bg = "white", fg = "black")
btnXC.place(x=152, y=187, width=75,height=48)
btnUnoSX = tk.Button(ventanaPrincipal,text="1/x", bg = "white", fg = "black")
btnUnoSX.place(x=228, y=187, width=75,height=48)
btnMC = tk.Button(ventanaPrincipal,text="MC", bg = "white", fg = "gray")
btnMC.place(x=0, y=164, width=55,height=24)
btnMR = tk.Button(ventanaPrincipal,text="MR", bg = "white", fg = "gray")
btnMR.place(x=54, y=164, width=55,height=24)
btnMMas = tk.Button(ventanaPrincipal,text="M+", bg = "white", fg = "gray")
btnMMas.place(x=104, y=164, width=45,height=24)
btnMMenos = tk.Button(ventanaPrincipal,text="M-", bg = "white", fg = "gray")
btnMMenos.place(x=149, y=164, width=45,height=24)
btnMS = tk.Button(ventanaPrincipal,text="MS", bg = "white", fg = "gray")
btnMS.place(x=194, y=164, width=45,height=24)
btnMO = tk.Button(ventanaPrincipal,text="M^", bg = "white", fg = "gray")
btnMO.place(x=238, y=164, width=65,height=24)
cajaTextoResultado = Label(ventanaPrincipal, text = 0)
cajaTextoResultado.place(x= 280, y = 130)
cajaTextoEstandar = Label(ventanaPrincipal, text = "ESTANDAR")
cajaTextoEstandar.place(x=10, y = 10)
ventanaPrincipal.mainloop()